# Generated by Django 3.0.2 on 2020-06-23 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('perfil', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status_andamento', models.CharField(max_length=100, verbose_name='Status Andamento')),
                ('orcamento', models.IntegerField(verbose_name='Orçamento')),
                ('data_inicio', models.DateTimeField(auto_now=True, verbose_name='Data de Inicio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.BinaryField()),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Projeto')),
            ],
        ),
    ]
